EXECUTION_LOG_ENABLE: true
EXECUTION_LOG_PATH: '%RAFCON_TEMP_PATH_BASE/execution_logs'
EXECUTION_LOG_SET_READ_AND_WRITABLE_FOR_ALL: false
LIBRARY_PATHS:
    VIRTUAL_LINK_TO_ACTIONS: template
    generic: ${RAFCON_LIB_PATH}/generic
    mission_control: .
    ros: ${RAFCON_LIB_PATH}/../examples/libraries/ros_libraries
LIBRARY_RECOVERY_MODE: true
LOAD_SM_WITH_CHECKS: false
MAX_LENGTH_FOR_STATE_NAME_IN_STORAGE_PATH: None
NO_PROGRAMMATIC_CHANGE_OF_LIBRARY_STATES_PERFORMED: true
SCRIPT_RECOMPILATION_ON_STATE_EXECUTION: true
STORAGE_PATH_WITH_STATE_NAME: true
TYPE: SM_CONFIG
